apiVersion: "autoscaling.openshift.io/v1"
kind: "ClusterAutoscaler"
metadata:
  name: "default"
spec:
  balanceSimilarNodeGroups: true
  podPriorityThreshold: -10
  resourceLimits:
    maxNodesTotal: 18
    cores:
      min: 8
      max: 128
    memory:
      min: 4
      max: 256
  scaleDown: 
    enabled: true
    delayAfterAdd: 10m
    delayAfterDelete: 30s
    delayAfterFailure: 30s
    unneededTime: 60s
